bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-d kill-pane

bind -n M-s switch-client -T split-nav

bind -T split-nav Up split-window -vb
bind -T split-nav Down split-window -v
bind -T split-nav Left split-window -hb
bind -T split-nav Right split-window -h
bind -T split-nav M-Up split-window -vb
bind -T split-nav M-Down split-window -v
bind -T split-nav M-Left split-window -hb
bind -T split-nav M-Right split-window -h
